name: API CI

on:
  push:
    branches: [ main, master ]
    paths:
      - "api_tests/**"
      - ".github/workflows/api-ci.yml"
  pull_request:
    paths:
      - "api_tests/**"
      - ".github/workflows/api-ci.yml"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.11", "3.12", "3.13" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: api_tests/requirements.txt

      - name: Install deps
        working-directory: api_tests
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Prepare env (optional)
        if: ${{ secrets.API_BASE_URL != '' }}
        working-directory: api_tests
        run: |
          echo "BASE_URL=${{ secrets.API_BASE_URL }}" >> .env

      - name: Run tests (parallel with xdist)
        working-directory: api_tests
        env:
          PYTHONWARNINGS: ignore
        run: |
          pytest -m "not ui" -n auto \
            --alluredir=allure-results \
            --maxfail=1 -q

      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-${{ matrix.python-version }}
          path: api_tests/allure-results
          retention-days: 7

      - name: Upload junit xml (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-${{ matrix.python-version }}
          path: api_tests/junit.xml
          if-no-files-found: ignore